# Generated by Django 2.0.3 on 2019-06-19 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article1', '0002_auto_20190617_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost1',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='articles_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
